name: CI

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up ROS 2 Humble
      uses: ros-tooling/setup-ros@0.7.7
      with:
        distribution: humble
        install-packages: |
          python3-colcon-common-extensions
          python3-rosdep
          ros-humble-launch
          ros-humble-launch-testing
          ros-humble-launch-ros

    - name: Create ROS workspace
      run: |
        mkdir -p ~/ros_ws/src
        cd ~/ros_ws/src
        ln -s $GITHUB_WORKSPACE/* .
        cd ~/ros_ws

    - name: Update dependencies
      run: |
        if [ ! -f /etc/ros/rosdep/sources.list.d/20-default.list ]; then
          sudo rosdep init
        fi
        rosdep update

    - name: Install dependencies
      run: |
        cd ~/ros_ws
        rosdep install --from-paths src --ignore-src -r -y

    - name: Build
      run: |
        cd ~/ros_ws
        source /opt/ros/humble/setup.bash
        colcon build --event-handlers console_cohesion+

    - name: Run tests
      run: |
        cd ~/ros_ws
        source /opt/ros/humble/setup.bash
        colcon test --event-handlers console_cohesion+

    - name: Check test results
      run: |
        cd ~/ros_ws
        source /opt/ros/humble/setup.bash
        colcon test-result --all
