name: CI

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up ROS 2 Humble
      run: |
        sudo apt update
        sudo apt install -y curl gnupg lsb-release
        sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
        sudo sh -c 'echo "deb http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2-latest.list'
        sudo apt update
        sudo apt install -y ros-humble-desktop
        sudo apt install -y python3-colcon-common-extensions python3-rosdep
        sudo rosdep init || echo "rosdep already initialized"
        rosdep update

    - name: Create ROS workspace
      run: |
        mkdir -p ~/ros_ws/src
        cd ~/ros_ws/src
        ln -s $GITHUB_WORKSPACE/* .
        cd ~/ros_ws

    - name: Update dependencies
      run: |
        source /opt/ros/humble/setup.bash
        rosdep install --from-paths src --ignore-src -r -y

    - name: Build
      run: |
        source /opt/ros/humble/setup.bash
        colcon build --event-handlers console_cohesion+

    - name: Run tests
      run: |
        source /opt/ros/humble/setup.bash
        colcon test --event-handlers console_cohesion+

    - name: Check test results
      run: |
        source /opt/ros/humble/setup.bash
        colcon test-result --all
